# ryan_library/orchestrators/tuflow/po_combine.py
"""
PO Combination Utilities.

This module provides the core logic for combining "PO" (Plot Output) CSV files generated by TUFLOW simulations.
It leverages the `ProcessorCollection` to process files in parallel, normalize locations, and filter data types.
The combined results can be exported to Excel or Parquet formats.
"""

__lazy_modules__: list[str] = ["pandas"]

from collections.abc import Collection
from pathlib import Path
from typing import Literal

from ._combination_workflow import execute_combination_workflow

DEFAULT_DATA_TYPES: tuple[str, ...] = ("PO",)
ACCEPTED_DATA_TYPES: frozenset[str] = frozenset(DEFAULT_DATA_TYPES)


def main_processing(
    paths_to_process: list[Path],
    include_data_types: list[str] | None = None,
    console_log_level: str = "INFO",
    locations_to_include: Collection[str] | None = None,
    export_mode: Literal["excel", "parquet", "both"] = "excel",
) -> None:
    """
    Generate merged PO data and export the results.

    This function orchestrates the finding, reading, processing, and combining of TUFLOW PO CSV files.
    It supports filtering by specific locations and exporting the final combined dataset.

    Args:
        paths_to_process: A list of directory paths to search for PO files.
        include_data_types: A list of data types to include (e.g., ["PO"]). Defaults to DEFAULT_DATA_TYPES.
        console_log_level: logging level for the console output (e.g., "INFO", "DEBUG").
        locations_to_include: A collection of location names (strings) to keep. If None, all locations are kept.
                              Column matching is case-insensitive.
        export_mode: The format for the output file(s): "excel", "parquet", or "both".
    """
    execute_combination_workflow(
        paths_to_process=paths_to_process,
        include_data_types=include_data_types,
        default_data_types=DEFAULT_DATA_TYPES,
        accepted_data_types=ACCEPTED_DATA_TYPES,
        context_name="PO combination",
        export_prefix="combined_PO",
        export_sheet_name="combined_PO",
        export_metadata={"Workflow": "PO combine"},
        combine_callable=lambda results: results.po_combine(),
        console_log_level=console_log_level,
        locations_to_include=locations_to_include,
        export_mode=export_mode,
    )
